 [97m[CODING][0m @sect
Fix and upgrade the FIFA Back-up Tool @todo
 [95m[GAMEMAKING][0m @sect
Learn Unity @todo
 [96m[TERMINAL][0m @sect
Better sudo command (might even put the batch in the custom commands folder) @todo
Upgrade/Finish the todo command @todo
Fix the p/projects command @todo
 [94m[SCHOOL][0m @sect
 [93m[FILMS/TVSHOWS][0m @sect
 [92m[TODOBAT][0m @sect
Add an edit entry mode @todo
Make the expiring date refresher (finish the autodelete entry mode) @todo
Add the ability to create more then one todo list @todo
Make the settings read/write directly from inside the .bat (use ReplaceLine) [exp:02-05-2024] @done
Last todo entry of the whole .td file can't be ticked @todo
